version: '3.8'

services:
  app:
    build: .
    image: kelashack.id_07_ssti:latest
    container_name: kelashack.id_07_ssti
    volumes:
      - ./app:/app
    ports:
      - "9907:9907"
    restart: always