version: '3.1'

services:

  wordpress:
    build: .
    image: kelashack.id_02_vulnerability_in_cms:latest
    container_name: kelashack.id_02_vulnerability_in_cms
    restart: always
    ports:
      - 9902:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: kelashack.id_02_vulnerability_in_cms_mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - volume:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql

volumes:
  volume:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
