version: '3.8'

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile-app-1
    image: kelashack.id_10_network_exploration_app_1
    container_name: kelashack.id_10_network_exploration_app_1
    networks:
      custom_network:
        ipv4_address: 192.168.10.11
    ports:
      - "9910:80"
    restart: always

  app-2:
    build:
      context: .
      dockerfile: Dockerfile-app-2
    image: kelashack.id_10_network_exploration_app_2
    container_name: kelashack.id_10_network_exploration_app_2
    networks:
      custom_network:
        ipv4_address: 192.168.10.12
    expose:
      - "80"
    restart: always

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
